server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/payments/**
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/workers/**

    http:
      client:
        connect-timeout: 2000
        response-timeout: 3s
