server:
  port: 9000

spring:
  application:
    name: hr-oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 80876775106-p337hn37l7njbdvghahj3iljvl0crqi6.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - openid

          github:
            client-id: 1b1b1b1b1b1b1b1b1b1b
            client-secret: 2b2b
            scope:
              - user
              - user:email
eureka:
  instance:
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


